@echo off
chcp 65001 > nul
REM ============================================================
REM  TeamTaskMail EXE Build Script (STEP 8)
REM
REM  Build-time embeds WEBAPP_URL and API_TOKEN into the EXE so
REM  target PCs do not need to set environment variables.
REM  Just copy the .exe and double-click.
REM
REM  Required env vars on the build machine:
REM    set TEAMTASK_WEBAPP_URL=https://script.google.com/...
REM    set TEAMTASK_API_TOKEN=<EXE_API_TOKEN>
REM
REM  Run from exe\ directory:
REM    .\build.bat
REM ============================================================

setlocal

set VERSION=1.0.0
set EXE_NAME=TeamTaskMail
set ENTRY=agent_entry.py
set DIST_DIR=dist\v%VERSION%
set BAKED_CONFIG=mail_agent\_baked_config.py

echo === TeamTaskMail v%VERSION% Build Start ===
echo.

REM --- Validate build-time env vars -------------------------
if "%TEAMTASK_WEBAPP_URL%"=="" (
    echo ERROR: TEAMTASK_WEBAPP_URL is not set.
    echo   set TEAMTASK_WEBAPP_URL=https://script.google.com/...
    exit /b 1
)
if "%TEAMTASK_API_TOKEN%"=="" (
    echo ERROR: TEAMTASK_API_TOKEN is not set.
    echo   set TEAMTASK_API_TOKEN=^<EXE_API_TOKEN value^>
    exit /b 1
)

REM --- [1/4] Install dependencies ---------------------------
echo [1/4] Installing dependencies...
python -m pip install -r requirements.txt
if %ERRORLEVEL% neq 0 (
    echo ERROR: pip install failed.
    exit /b %ERRORLEVEL%
)
echo.

REM --- [2/4] Generate _baked_config.py ----------------------
REM This file is bundled into the EXE by PyInstaller and removed
REM after the build (and is gitignored to prevent token leakage).
echo [2/4] Generating baked config (_baked_config.py)...
> %BAKED_CONFIG% echo # Auto-generated by build.bat. DO NOT EDIT or COMMIT.
>> %BAKED_CONFIG% echo # WEBAPP_URL / API_TOKEN are baked into the EXE at build time.
>> %BAKED_CONFIG% echo WEBAPP_URL = "%TEAMTASK_WEBAPP_URL%"
>> %BAKED_CONFIG% echo API_TOKEN = "%TEAMTASK_API_TOKEN%"
echo   Generated: %BAKED_CONFIG%
echo.

REM --- [3/4] Generate version_info.txt ----------------------
echo [3/4] Generating version_info.txt...
(
echo VSVersionInfo^(
echo   ffi=FixedFileInfo^(
echo     filevers=^(1, 0, 0, 0^),
echo     prodvers=^(1, 0, 0, 0^),
echo     mask=0x3f,
echo     flags=0x0,
echo     OS=0x40004,
echo     fileType=0x1,
echo     subtype=0x0,
echo     date=^(0, 0^)
echo   ^),
echo   kids=[
echo     StringFileInfo^([
echo       StringTable^(u'040904B0', [
echo         StringStruct^(u'CompanyName',      u'Mechanical Design Dept.'^),
echo         StringStruct^(u'ProductName',      u'TeamTaskMail'^),
echo         StringStruct^(u'FileVersion',      u'%VERSION%'^),
echo         StringStruct^(u'ProductVersion',   u'%VERSION%'^),
echo         StringStruct^(u'FileDescription',  u'Team Task Management Mail Agent'^),
echo       ]^)
echo     ]^),
echo     VarFileInfo^([VarStruct^(u'Translation', [1033, 1200]^)^]^)
echo   ]
echo ^)
) > version_info.txt

REM --- [4/4] PyInstaller ------------------------------------
echo [4/4] Running PyInstaller...
pyinstaller ^
  --onefile ^
  --noconsole ^
  --name %EXE_NAME% ^
  --version-file version_info.txt ^
  %ENTRY%

if %ERRORLEVEL% neq 0 (
    echo ERROR: PyInstaller build failed.
    if exist version_info.txt del version_info.txt
    if exist %BAKED_CONFIG% del %BAKED_CONFIG%
    exit /b %ERRORLEVEL%
)

REM --- Copy to versioned dist folder ------------------------
if not exist %DIST_DIR% mkdir %DIST_DIR%
copy /Y dist\%EXE_NAME%.exe %DIST_DIR%\%EXE_NAME%.exe > nul

echo.
echo === Build Complete ===
echo Output: %DIST_DIR%\%EXE_NAME%.exe

REM --- Cleanup ----------------------------------------------
if exist version_info.txt del version_info.txt
if exist build rmdir /s /q build
if exist %EXE_NAME%.spec del %EXE_NAME%.spec
if exist %BAKED_CONFIG% del %BAKED_CONFIG%

echo.
echo Distribution (no env vars needed on target PCs):
echo   1. Copy %DIST_DIR%\%EXE_NAME%.exe to a shared folder
echo   2. Each staff copies it to their local PC
echo   3. Double-click to run (use Task Scheduler for auto-start)
echo.
echo Security note:
echo   The API token is embedded in this EXE.
echo   Limit distribution to the engineering department only.
echo   If the token is rotated, rebuild and redistribute.

endlocal
